name: Verify
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  generate-and-test:
    name: Generate and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: adopt@1.11
      - name: generate xtend
        run: sbt bsp4j/xtend
      - name: compile
        run: sbt +compile +package
      - name: test
        run: sbt +test
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v11
        with:
            java-version: adopt@1.8
      - run: sbt checkScalaFormat
      - run: cd website
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn prettier --check .
